### ISSUE TITLE
plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [mstuyts/ZoomToBelgium#1]
Please add missing metadata file. Plugin does not install successfully

**Comment by mstuyts** [comment]
@NyakudyaA, I'm not sure what you mean.

It does contain a metadata.txt file. Both on Github and in the file I uploaded to the QGIS plugin repository.  I uploaded the same zip-file to my private repository and it installs without a problem.  

What file do you think is missing?

**Comment by NyakudyaA** [comment]
@mstuyts  The way you have arranged your repo. Please consider moving all the contents from ZoomToBelgium to the base of the repo. 

![clone](https://user-images.githubusercontent.com/2510900/32594193-bc1edab8-c533-11e7-9a09-c539ddeb1893.png)

Should be
![zoom](https://user-images.githubusercontent.com/2510900/32594238-e6e295d2-c533-11e7-8672-e7ef860e10cd.png)

**Comment by mstuyts** [comment]
@NyakudyaA The files in the ZoomToBelgium folder are the core plugin files, that are also in the zip-file uploaded to the official QGIS repo. All other files are documentation and files used during development, that are not in the ZIP-file for the QGIS repo. To keep this difference clear the core plugin files are placed in a separate folder.

On the [releases page](https://github.com/mstuyts/ZoomToBelgium/releases) you will see that every release will have 2 source downloads that contain all files from this ZoomToBelgium repo and 1 plugin zip-file download with a version number that only contains the files needed to install the plugin.  It is that same zip-file with core plugin files I uploaded to the QGIS plugins repo.  That's my choice of organizing this ZoomToBelgium repo. 

According to your screenshots you downloaded the wrong file to install. The file with the plugin release and the file uploaded to the QGIS plugin repo do not contain *.bat files and README.md. Could you please try the correct file: https://github.com/mstuyts/ZoomToBelgium/releases/download/v.0.1.1/ZoomToBelgium-v.0.1.1.zip.

**Comment by NyakudyaA** [comment]
Ok Thanks for explaining. I had just cloned the repo which I assume is your dev environment. Have approved the plugin

**Comment by mstuyts** [comment]
Thank you very much.
